import React from "react";

export default function TermsPage() {
  return (
    <main className="w-full bg-surface min-h-screen py-24 px-6">
      <div className="max-w-3xl mx-auto">
        <h1 className="text-4xl md:text-5xl font-extrabold text-heading tracking-tight mb-4">Terms and Conditions</h1>
        <p className="text-muted mb-12 font-medium">Last Updated: March 2026</p>

        <div className="text-body space-y-8 leading-relaxed">
          <p>
            Welcome to NovaNutri. By downloading, accessing, or using the NovaNutri mobile application (&quot;App&quot;), you agree to be bound by these Terms and Conditions (&quot;Terms&quot;). If you do not agree to these Terms, please do not use the App.
          </p>

          <section>
            <h2 className="text-2xl font-bold text-heading mb-3">1. Account Creation and Data Storage</h2>
            <p>
              To use certain features of NovaNutri, you must create an account. You are responsible for maintaining the confidentiality of your login credentials. Your personal data, including dietary preferences, saved recipes, and meal plans, is stored securely using Google Firebase services. By using the App, you consent to the collection and storage of your data as required to provide our services.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-heading mb-3">2. Subscriptions and Payments</h2>
            <p className="mb-3">While certain features of NovaNutri may be offered for free, we reserve the right to charge a subscription fee for premium features (e.g., unlimited AI recipe imports, advanced analytics).</p>
            <ul className="list-disc pl-5 space-y-2">
              <li>Any applicable fees, billing cycles, and terms will be clearly communicated prior to purchase.</li>
              <li>Subscriptions automatically renew unless canceled by the user prior to the renewal date.</li>
              <li>We reserve the right to modify our subscription pricing at any time with prior notice to users.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-heading mb-3">3. Medical and Nutritional Disclaimer</h2>
            <p className="mb-3"><strong>NovaNutri is not a medical provider.</strong> The dietary information, nutritional calculations, macronutrients, and allergy filtering provided by the App—including data generated by Artificial Intelligence—are for informational and planning purposes only.</p>
            <ul className="list-disc pl-5 space-y-2">
              <li>We do not guarantee the 100% accuracy of nutritional information or the complete absence of allergens in any recipe.</li>
              <li>Users with severe food allergies, medical conditions, or specific dietary requirements must independently verify the ingredients and nutritional content of all meals.</li>
              <li>NovaNutri shall not be held liable for any adverse reactions, health issues, or dietary complications resulting from the use of recipes or meal plans found within the App.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-heading mb-3">4. AI-Generated Content and Pricing Accuracy</h2>
            <p className="mb-3">NovaNutri utilizes Artificial Intelligence to extract recipes from third-party social media URLs (e.g., TikTok, YouTube) and estimates grocery costs based on monitored databases.</p>
            <ul className="list-disc pl-5 space-y-2">
              <li><strong>Recipe Extraction:</strong> We do not claim ownership of third-party recipes imported by users. The AI extraction tool is provided as a utility to format publicly available data.</li>
              <li><strong>Pricing Estimates:</strong> Grocery prices and &quot;Cost Per Person&quot; metrics are estimates and may fluctuate based on location, store availability, and inflation. NovaNutri is not responsible for discrepancies between the App&apos;s estimated costs and actual checkout prices.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-heading mb-3">5. Intellectual Property</h2>
            <p>
              The NovaNutri App, including its original code, UI/UX design, algorithms, logos, and proprietary features (such as the &quot;Virtual Fridge&quot; and &quot;Magic Import&quot; workflows), are the exclusive property of NovaNutri and are protected by international copyright laws. You may not copy, reverse engineer, or distribute any part of the App.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-heading mb-3">6. User Conduct</h2>
            <p className="mb-3">Users agree not to:</p>
            <ul className="list-disc pl-5 space-y-2">
              <li>Submit abusive, illegal, or inappropriate content in community reviews or recipe uploads.</li>
              <li>Attempt to bypass subscription paywalls or abuse the AI import API limits.</li>
            </ul>
            <p className="mt-3">We reserve the right to suspend or terminate the accounts of users who violate these rules.</p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-heading mb-3">7. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, NovaNutri and its creators shall not be liable for any indirect, incidental, special, or consequential damages arising out of or related to your use of the App, including but not limited to financial losses from grocery purchases or health-related damages.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-heading mb-3">8. Changes to Terms</h2>
            <p>
              We reserve the right to modify these Terms at any time. Continued use of the App following any changes constitutes your acceptance of the new Terms.
            </p>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-heading mb-3">9. Contact</h2>
            <p>
              For any questions regarding these Terms, please contact support through the NovaNutri App or website.
            </p>
          </section>
        </div>
      </div>
    </main>
  );
}